### ISSUE TITLE
Impossible to remove subscription while editing a subscriber

### ISSUE THREAD

**Issue by franck-grenier** [Open-Wide/OWNewsletter#9]
![subscriptions_status](https://cloud.githubusercontent.com/assets/214572/6061396/b782fc34-ad47-11e4-9049-bb33a6025a35.png)
While editing a subscriber on "/newsletter/user/[id_subscriber]", fields allow to manage the subscriptions. Here, it's possible to approve but impossbile to remove subscriptions. Only "approve" status is selectable in dropdown lists.

**Comment by laurentsab** [comment]
When a subscriber is on "desactivé" status, we can select "approve", but when we save the subscriber status is not update (approve) on this mailing list.
